# Generic application properties
jwtSecret: "HelloSefali@2007"

# Set the environment to use
env: dev

# Production environment properties
prod:
  server:
    host: sistadm.us
    basepath: ""
    port: 8080
  
  cors:
    allowOrigin: "https://sistadm.us"

  db:
    host: 157.245.17.155
    port: 5432
    dbname: sistadm
    user: sistadm_write
    password: Bhulgaya@2326

# Development environment properties
dev:
  server:
    host: localhost
    basepath: ""
    port: 8080
  
  cors:
    allowOrigin: "http://localhost:3000"

  db:
    host: 157.245.17.155
    port: 5432
    dbname: sistadm
    user: sistadm_write
    password: Bhulgaya@2326

# Staging environment properties
stage:
  server:
    host: sistadm.us
    basepath: ""
    port: 8080
  
  cors:
    allowOrigin: "https://sistadm.us"

  db:
    host: 157.245.17.155
    port: 5432
    dbname: sistadm
    user: sistadm_write
    password: Bhulgaya@2326
