# Generic application properties

server:
  port: 80

basepath: ""


# Set the environment to use
env: prod

# Production environment properties
prod:
  db:
    host: 157.245.17.155
    port: 5432
    dbname: sistadm
    user: sistadm_write
    password: Bhulgaya@2326

# Development environment properties
dev:
  db:
    host: 127.0.0.1
    port: 5432
    dbname: sistadm
    user: postgres
    password: postgres

# Staging environment properties
verify:
  db:
    host: db.sistadm.us
    port: 5432
    dbname: sistadm
    user: sistadm
    password: Sist@2023@Adm
