# Generic application properties
jwtSecret: "HelloSefali@2007"

# Set the environment to use
env: dev

# Production environment properties
prod:
  server:
    host: stoutnext.com
    basepath: ""
    port: 8080
  
  cors:
    allowOrigin: "https://adm.stoutnext.com"

  db:
    host: adm-db.postgres.database.azure.com
    port: 5432
    dbname: sistadm
    user: sistadm_write
    password: Bhulgaya@2326
  
  razorpay:
    key: rzp_test_mtawFMx1J5ch4R
    secret: HDYV4GlTuTL5gu7PWcGgBs9g
  
  application:
    fee: 500

# Development environment properties
dev:
  server:
    host: localhost
    basepath: ""
    port: 8080
  
  cors:
    allowOrigin: "http://localhost:3000"

  db:
    host: 157.245.17.155
    port: 5432
    dbname: sistadm
    user: sistadm_write
    password: Bhulgaya@2326

  razorpay:
    key: rzp_test_mtawFMx1J5ch4R
    secret: HDYV4GlTuTL5gu7PWcGgBs9g
  
  application:
    fee: 500

# Staging environment properties
stage:
  server:
    host: adm.stoutnext.com
    basepath: ""
    port: 8080
  
  cors:
    allowOrigin: "https://adm.stoutnext.com"

  db:
    host: adm-db.postgres.database.azure.com
    port: 5432
    dbname: sistadm
    user: stoutnext
    password: Bhulgaya@2326

  razorpay:
    key: rzp_test_mtawFMx1J5ch4R
    secret: HDYV4GlTuTL5gu7PWcGgBs9g
  
  application:
    fee: 500
