# Generic application properties
jwtSecret: "HelloSefali@2007"

# Set the environment to use
env: prod

# Production environment properties
prod:
  server:
    host: backend.adm.stoutnext.com
    basepath: ""
    port: 8080
  
  client:
    host: adm.stoutnext.com
  
  cors:
    allowOrigin: "http://localhost:3000"

  db:
    host: 98.70.92.217
    port: 5432
    dbname: sistadm
    user: sistadm_write
    password: Bhulgaya2326
  
  razorpay:
    key: rzp_test_mtawFMx1J5ch4R
    secret: HDYV4GlTuTL5gu7PWcGgBs9g
  
  application:
    fee: 500

# Development environment properties
dev:
  server:
    host: backend.adm.stoutnext.com
    basepath: ""
    port: 8080
  client:
    host: localhost:3000
  
  cors:
    allowOrigin: "http://localhost:3000"

  db:
    host: 139.59.19.232
    port: 5432
    dbname: sistadm
    user: sistadm_write
    password: FAC06AA7-BAC2-4D37-9AE3-93F8C0F4C5C8

  razorpay:
    key: rzp_test_mtawFMx1J5ch4R
    secret: HDYV4GlTuTL5gu7PWcGgBs9g
  
  application:
    fee: 500

# Staging environment properties
stage:
  server:
    host: sistadm.us
    basepath: ""
    port: 8080
  
  cors:
    allowOrigin: "http://localhost:3000"

  db:
    host: 157.245.17.155
    port: 5432
    dbname: sistadm
    user: sistadm_write
    password: Bhulgaya@2326

  razorpay:
    key: rzp_test_mtawFMx1J5ch4R
    secret: HDYV4GlTuTL5gu7PWcGgBs9g
  
  application:
    fee: 500
